cookie:
  expiry_days: 30
  key: whykay
  name: yasirkhalid
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$2F7j8DI9nbDk/UXjDFWiWuCCYfz78C5G/J1zJi.pOpf/GMnBDexwm
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$zAhCwCOePM9i2UuzjFptU.tA4apO6bN9diovj.8WCNUQNuKAvI6Li
    ykhalid:
      email: yasir@schoolx.pk
      name: Yasir Khalid
      password: $2b$12$soR3.xffmIYT9TdiJKQXo.1jeo4SfYrCGZw7KpwMKb06LNP0ODBIS
preauthorized:
  emails:
  - yasir@gmail.com
